version: '3.3'
services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: ng
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    # volumes:
    #   - type: volume
    #     source: wordpress
    #     target: /var/www/html/wordpress

  wordpress:
    build: requirements/wordpress
    image: wordpress:v1
    # image: wordpress:v1 # skip-check
    networks:
      - inception
    expose:
      - "9000"
    container_name: wp
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
    
    # volumes:
    #   - type: volume
    #     source: wordpress
    #     target: /var/www/html/wordpress
    # restart: on-failure

  mariadb:
    build: requirements/mariadb
    image: mariadb:v01
    container_name: mariadb
    networks:
      - inception
    # volumes:
    #   - type: volume
    #     source: mariadb
    #     target: /var/lib/mysql
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_HOST=${DB_HOST}
    # restart: unless-stopped

networks:
  inception:
    name: inception
    ipam:
      driver: default
# volumes:
#   mariadb:
  # wordpress:

