version: '3.7'

services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - /home/hasabir/data/wordpress:/var/www/html/wordpress

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    expose:
      - 9000
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - /home/hasabir/data/wordpress:/var/www/html/wordpress

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - 3306
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/hasabir/data/mariadb

    # device: '/Users/login/data/mariadb
#   wordpress:

