version: '3.3'
services:
#   nginx:
#     build: ./nginx
#     container_name: ng
#     ports:
#       - "443:443"

  wordpress:
    build: ./wordpress
    container_name: wp
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 123
      WORDPRESS_DB_NAME: wordpress

  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb
  #   env_file:
  #     - .env
  #   # environment:
  #   #   MYSQL_DATABASE: wordpress
  #   #   MYSQL_ROOT_PASSWORD: 123
