version: '3.7'
services:
  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    # command: [ "nginx", "-g", "daemon off;"]
    command: ["/app/tools/script.sh"]
    # command: ["/app/tools/script.sh", "--", "nginx", "-c", "/app/conf/nginx.conf", "-g", "daemon off;"]
    
      # - /home/hasabir/data:/var/www/html/wordpress
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html/wordpress

  wordpress:
    build: requirements/wordpress
    image: wordpress
    networks:
      - inception
    # expose:
    ports:
      - "9000:9000"
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    command: ["bash" , "/app/script.sh"]
    volumes:
      - type: volume
        source: wordpress
        target: /var/www/html/wordpress
    # restart: always


  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - type: volume
        source: mariadb
        target: /var/lib/mysql
    # expose:
    ports:
      - "3306:3306"
    env_file:
      - .env
    command: ["/app/tools/test_script.sh" ]
    # restart: unless-stopped

networks:
  inception:
    name: inception
    ipam:
      driver: default
volumes:
  mariadb:
  wordpress:

