version: '3.3'
services:
  test:
    build: ./nginx
    container_name: ng_test
    ports:
      - "443:443"
  # wordpress:
  #   image: wordpress
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: 123
  #     WORDPRESS_DB_NAME: wordpress

  # mariadb:
  #   image: mariadb
  #   environment:
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_ROOT_PASSWORD: 123