version: '3'

services:
  nginx:
    image: debian:bullseye
    command: ["nginx", "-c", "/app/conf/nginx.conf", "-g", "daemon off;"]
    ports:
      - "80:80"
    volumes:
      - ./nginx:/app
      - ./tools:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: debian:bullseye
    volumes:
      - ./mysql:/app
    command: ["/app/tools/test_script.sh"]
    networks:
      - mynetwork

  wordpress:
    image: debian:bullseye
    command: ["php-fpm7.3", "-R", "-F"]
    volumes:
      - ./wordpress:/app
      - ./tools:/app/tools
    depends_on:
      - mysql
    networks:
      - mynetwork
    links:
      - mysql

networks:
  mynetwork:



# version: '3.3'
# services:
#   test:
#     build: ./nginx
#     container_name: ng_test
#     ports:
#       - "443:443"
  # wordpress:
  #   image: wordpress
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - mariadb
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_USER: root
  #     WORDPRESS_DB_PASSWORD: 123
  #     WORDPRESS_DB_NAME: wordpress

  # mariadb:
  #   image: mariadb
  #   environment:
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_ROOT_PASSWORD: 123